### ISSUE TITLE
Sync Tv Episodes based on Watched Status?

### ISSUE THREAD

**Issue by fkick** [ilyaz/PlexDownloader#22]
Would it be possible to add the ability to sync TV episodes based on Plex's watched status? For instance, if I'm going through  series that has already completed, and I would like to only sync unwatched episodes rather then using the "recent" tvtype as that would only sync the most recent aired episodes.

**Comment by jtegiffel** [comment]
Change the setting 
unwatched = disable --> unwatched = enable
in your ini file an you should only sync unwatched episodes

**Comment by fkick** [comment]
Thanks jtegiffel. Man I feel stupid I missed that setting :)
